Repository jz-project/ohnpol-v2-frontend, pull requests merged in 2025-03, with the labels that each got.

#9 (임시PR)랜딩페이지 제작
  eslint.config.js
  package-lock.json
  package.json
  public/ohnpol_v2.svg
  src/app.tsx
  src/pages/landing/page.tsx
Labels: 🤔BugFix, feature

#14 랜딩페이지 (+ 로그인, 회원가입 컴포넌트) 제작
  package-lock.json
  package.json
  src/components/FormInput/index.tsx
  src/components/IconEye/index.tsx
  src/components/ToggleButton/index.tsx
  src/pages/landing/components/JoinModal/index.tsx
  src/pages/landing/components/LoginModal/index.tsx
  src/pages/landing/page.tsx
  src/utils/validator.ts
  tsconfig.app.json
Labels: feature, 🔴Priority : High

#16 TailwindCSS theme 색상 테마 설정
  src/styles/tailwind.css
Labels: feature

#20 [Build] 최적화 및 환경 설정 변경
  .gitignore
  package-lock.json
  package.json
  src/app.tsx
  src/styles/tailwind.css
  vite.config.ts
Labels: 🔨Configuration, Optimization

#22 Feat/mainpage
  .env
  index.html
  package.json
  public/assets/ohnpol-meta-image.png
  public/assets/ohnpol.svg
  public/assets/ohnpol_v2.svg
  src/components/Footer/index.tsx
  src/components/Header/index.tsx
  src/components/OhnpolLogo/index.tsx
  src/components/ohnpol-header/index.tsx
  src/layouts/common/layout.tsx
  src/layouts/common/title.tsx
  src/pages/landing/page.tsx
  src/pages/main/page.tsx
  src/styles/common/base.css
  src/styles/common/normalize.css
  src/styles/main.css
  src/vite-env.d.ts
Labels: feature, 🧹Refactor, 🔴Priority : High, 🔨Configuration

#24 커뮤니티 페이지 퍼블리싱
  src/app.tsx
  src/components/ArtistProfile/index.tsx
  src/components/FormInput/index.tsx
  src/components/IconStar/index.tsx
  src/components/ToggleButton/index.tsx
  src/pages/all-artist/page.tsx
  src/pages/community/page.tsx
  src/pages/landing/components/JoinModal/index.tsx
  src/pages/landing/components/LoginModal/index.tsx
  src/pages/landing/page.tsx
  src/temp/community/allPost.ts
  src/temp/community/memberProfile.ts
  src/temp/images/방탄소년단.webp
  src/utils/validator.ts
Labels: feature
